version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
    volumes:
      - cv_matcher_db:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge