CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    site VARCHAR(255),
    job_url VARCHAR(255),
    job_url_direct VARCHAR(255),
    title VARCHAR(255),
    company VARCHAR(255),
    location VARCHAR(255),
    job_type VARCHAR(255),
    date_posted VARCHAR(255),
    salary_source VARCHAR(255),
    interval VARCHAR(255),
    min_amount VARCHAR(255),
    max_amount VARCHAR(255),
    currency VARCHAR(255),
    is_remote VARCHAR(255),
    job_level VARCHAR(255),
    job_function VARCHAR(255),
    company_industry VARCHAR(255),
    listing_type VARCHAR(255),
    emails VARCHAR(255),
    description VARCHAR(255),
    company_url VARCHAR(255),
    company_url_direct VARCHAR(255),
    company_addresses VARCHAR(255),
    company_num_employees VARCHAR(255),
    company_revenue VARCHAR(255),
    company_description VARCHAR(255),
    logo_photo_url VARCHAR(255),
    banner_photo_url VARCHAR(255),
    ceo_name VARCHAR(255),
    ceo_photo_url VARCHAR(255)
);
